# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "epc1" do |epc1|
    epc.vm.box = "bento/debian-9.3"
    epc.vm.network "private_network", ip: "192.168.101.3"

    epc.vm.network "forwarded_port", guest: 80, host: 8080

    epc.vm.provision "shell", inline: <<-SHELL
      apt-get install -y git
      git clone https://github.com/infrared0/colte.git /home/vagrant/colte
      chown -R vagrant:vagrant /home/vagrant/colte
    SHELL

  end

  config.vm.define "epc2" do |epc2|
    epc1.vm.box = "bento/debian-9.3"
    epc1.vm.network "private_network", ip: "192.168.101.4"

    epc1.vm.network "forwarded_port", guest: 80, host: 8081

    epc1.vm.provision "shell", inline: <<-SHELL
      apt-get install -y git
      git clone https://github.com/infrared0/colte.git /home/vagrant/colte
      chown -R vagrant:vagrant /home/vagrant/colte
    SHELL

  end

end
