---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
    mysql_user: "{{ ansible_user_id }}"
    mysql_password: correcthorsebatterystaple

    colte_dir: "{{ playbook_dir }}/../../.."
    epc_dir: "{{ colte_dir }}/epc"
    enbrains_dir: "{{ colte_dir }}/enbrains"
    emergency_webservices_dir: "{{ colte_dir }}/emergency_webservices"
    packages_dir: "{{ colte_dir }}/packages"

# If you want to add new packages, just add them to this list!)
  tasks:
    - import_tasks: epc.yml
    - import_tasks: enbrains.yml
    - import_tasks: emergency_webservices.yml

  handlers:
    - import_tasks: emergency_webservices_handlers.yml
