---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
    mysql_user: "{{ ansible_user_id }}"
    mysql_password: correcthorsebatterystaple

    colte_dir: "{{ playbook_dir }}/../../.."
    epc_dir: "{{ colte_dir }}/epc"
    enbrains_dir: "{{ colte_dir }}/enbrains"
    emergency_webservices_dir: "{{ colte_dir }}/emergency_webservices"
    packages_dir: "{{ colte_dir }}/packages"

# If you want to add new packages to default install, just add them to this list!
- import_playbook: "{{epc_dir}}/install_scripts/debian-9.3.yml"
- import_playbook: "{{enbrains_dir}}/install_scripts/debian-9.3.yml"
- import_playbook: "{{emergency_webservices_dir}}/install_scripts/debian-9.3.yml"
