---
- hosts: localhost
  vars:
    mysql_user: enbrain
    username: enbrain
    mysql_password: correcthorsebatterystaple

#    colte_dir: /home/{{ username }}/colte
    colte_dir: {{ playbook_dir }}/../../..
    epc_dir: {{ colte_dir }}/epc
    enbrains_dir: {{ colte_dir }}/enbrains
    emergency_webservices_dir: {{ colte_dir }}/emergency_webservices
    packages_dir: {{ colte_dir }}/packages

# If you want to add new packages, just add to this list!)
    - import_tasks: epc.yml
    - import_tasks: enbrains.yml
    - import_tasks: emergency_webservices.yml
